Added support to upgrade FTBA modpacks

diff --git a/start-deployFTB b/start-deployFTB
--- a/start-deployFTB
+++ b/start-deployFTB
@@ -1,37 +1,49 @@
 #!/bin/bash
 
+ftbInstallMarker=".ftb-installed"
+
 . /start-utils
 isDebugging && set -x
 set -e
 
 if ! [[ -v FTB_MODPACK_ID ]]; then
-  log "ERR FTB_MODPACK_ID is required with TYPE=FTB"
+  log "ERROR FTB_MODPACK_ID is required with TYPE=FTB"
   exit 1
 fi
 
 if ! [[ ${FTB_MODPACK_ID} =~ [0-9]+ ]]; then
-  log "ERR FTB_MODPACK_ID needs to be numeric"
+  log "ERROR FTB_MODPACK_ID needs to be numeric"
   exit 1
-fi
-
-ftbInstaller=/data/ftb-installer
-if ! [[ -e "${ftbInstaller}" ]]; then
-  log "Downloading FTB installer"
-  curl -fsSL https://api.modpacks.ch/public/modpack/1/1/server/linux -o "${ftbInstaller}"
-  chmod +x "${ftbInstaller}"
 fi
 
 if ! [[ -v FTB_MODPACK_VERSION_ID ]]; then
-  FTB_MODPACK_VERSION_ID="--latest"
+  if ! FTB_MODPACK_VERSION_ID=$(curl -fsSL https://api.modpacks.ch/public/modpack/${FTB_MODPACK_ID} | jq -r '.versions | sort_by(.updated)[-1].id'); then
+    log "ERROR unable to resolve latest modpack version ID for modpack ${FTB_MODPACK_ID}"
+    exit 1
+  fi
 elif ! [[ ${FTB_MODPACK_VERSION_ID} =~ [0-9]+ ]]; then
-  log "ERR FTB_MODPACK_VERSION_ID needs to be numeric"
+  log "ERROR FTB_MODPACK_VERSION_ID needs to be numeric"
   exit 1
 fi
 
-rm -rf forge*jar mods config libraries defaultconfigs changelogs
+if ! [ -f "${ftbInstallMarker}" ] || [ $(cat "${ftbInstallMarker}") != "${FTB_MODPACK_ID}=${FTB_MODPACK_VERSION_ID}" ]; then
+  ftbInstaller=/data/ftb-installer
+  if ! [[ -f "${ftbInstaller}" ]]; then
+    log "Downloading FTB installer"
+    curl -fsSL https://api.modpacks.ch/public/modpack/1/1/server/linux -o "${ftbInstaller}"
+    chmod +x "${ftbInstaller}"
+  fi
 
-${ftbInstaller} ${FTB_MODPACK_ID} ${FTB_MODPACK_VERSION_ID} --noscript --auto
-rm -f forge*installer.jar
+  rm -rf forge*jar mods config libraries defaultconfigs changelogs
+
+  log "Installing modpack ID ${FTB_MODPACK_ID}, version ID ${FTB_MODPACK_VERSION_ID}"
+  ${ftbInstaller} ${FTB_MODPACK_ID} ${FTB_MODPACK_VERSION_ID} --noscript --auto
+  rm -f forge*installer.jar
+
+  echo "${FTB_MODPACK_ID}=${FTB_MODPACK_VERSION_ID}" > ${ftbInstallMarker}
+else
+  log "FTB modpack ID ${FTB_MODPACK_ID}, version ID ${FTB_MODPACK_VERSION_ID} is ready to go"
+fi
 
 isDebugging && cat version.json
 forgeVersion=$(jq -r '.targets[] | select(.name == "forge") | .version' version.json)
@@ -49,7 +61,7 @@ for f in ${variants[@]}; do
   fi
 done
 if ! [ -v SERVER ]; then
-  log "ERROR unable to locate the installer forge server jar"
+  log "ERROR unable to locate the installed forge server jar"
   ls *.jar
   exit 2
 fi
