Added another forge jar variant to look for

diff --git a/start-deployFTB b/start-deployFTB
--- a/start-deployFTB
+++ b/start-deployFTB
@@ -36,11 +36,22 @@ rm -f forge*installer.jar
 isDebugging && cat version.json
 forgeVersion=$(jq -r '.targets[] | select(.name == "forge") | .version' version.json)
 mcVersion=$(jq -r '.targets[] | select(.name == "minecraft") | .version' version.json)
-if [ -f "forge-${mcVersion}-${forgeVersion}.jar" ]; then
-  export SERVER="forge-${mcVersion}-${forgeVersion}.jar"
-elif [ -f "forge-${mcVersion}-${forgeVersion}-${mcVersion}-universal.jar" ]; then
-  # older style forge jars, such as 1.7.10
-  export SERVER="forge-${mcVersion}-${forgeVersion}-${mcVersion}-universal.jar"
+
+variants=(
+  forge-${mcVersion}-${forgeVersion}.jar
+  forge-${mcVersion}-${forgeVersion}-universal.jar
+  forge-${mcVersion}-${forgeVersion}-${mcVersion}-universal.jar
+)
+for f in ${variants[@]}; do
+  if [ -f $f ]; then
+    export SERVER=$f
+    break
+  fi
+done
+if ! [ -v SERVER ]; then
+  log "ERROR unable to locate the installer forge server jar"
+  ls *.jar
+  exit 2
 fi
 
 # Continue to Final Setup
